//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vista.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiante
    {
        public int Identificacion { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Programa { get; set; }
        public string Email { get; set; }

        internal int guardar(Estudiante item)
        {
            DatabaseEntities databaseEntities = new DatabaseEntities();
            databaseEntities.Estudiante.Add(item);
            databaseEntities.SaveChanges();
            return 1;
        }

    }
}
