//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vista.Datos
{
    using System;
    using System.Collections.Generic;

    public partial class Universidad
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }


        DatabaseEntities databaseEntities = new DatabaseEntities();

        internal bool Guardar(Universidad universidad)
        {
            
            databaseEntities.Universidad.Add(universidad);
            databaseEntities.SaveChanges();
            return true;
        }

    }
}
