//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiantes
    {
        public int Id { get; set; }
        public string Identificacion { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Programa { get; set; }
        public string Email { get; set; }

        public Estudiantes()
        {
        }

        public Estudiantes( string identificacion, string nombres, string apellidos, string programa, string email)
        {
            Identificacion = identificacion;
            Nombres = nombres;
            Apellidos = apellidos;
            Programa = programa;
            Email = email;
        }

        EstudiantesDatabaseEntities db = new EstudiantesDatabaseEntities();
        public int GuardarEstudiante(Estudiantes estudiantes)
        {

            db.Estudiantes.Add(estudiantes);
            return db.SaveChanges();
        }
    }
}
